### ISSUE TITLE
Popup runs off the screen.

### ISSUE THREAD

**Issue by davefaris** [j26design/Ecwid-Premium-Storefront#1]
I've set up my online store so that there's a bottom limit for a shopping cart order. If the subtotal is under $5 and the customer tries to check out, a warning popup appears. Except the warning popup is screwed up.
![screenshot](https://cloud.githubusercontent.com/assets/19150763/14955776/3e6c82c2-104a-11e6-9145-b5a3acce413d.jpg)

I've isolated the issue to the Ecwid-premium-storefront plugin for muse. I can't seem to alter the way the popup appears with special css overrides.

**Comment by jp26jp** [comment]
Thank you for reporting this. Can you send me the muse file? john@j-26.com

**Comment by jp26jp** [comment]
Never mind, I fixed the issue. If you redownload the widgets that were sent in the email, you will get the updated version of the widget that will fix this issue.

**Comment by davefaris** [comment]
Excellent. Thanks very much. 

    On Monday, May 2, 2016 11:22 AM, jp26jp <notifications@github.com> wrote:
 

 Never mind, I fixed the issue. If you redownload the widgets that were sent in the email, you will get the updated version of the widget that will fix this issue.—
