### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by 512studio** [j26design/Ecwid-Premium-Storefront#2]
So I added the new store widget to an existing site with your previous widget. All the new features are great. Still getting use to it. But I noticed that it will not add the Options for certain items that have them. Am I missing where to activate those or should be populating automatically?

Current site with options shown
<img width="1287" alt="current site" src="https://cloud.githubusercontent.com/assets/19173084/14991349/ec8f741a-112e-11e6-9a8c-8d130eea7d6e.png">

Site with updated widgets
<img width="1292" alt="with updated widgets" src="https://cloud.githubusercontent.com/assets/19173084/14991350/eca964c4-112e-11e6-90c5-8eb6a8a89126.png">

**Comment by jp26jp** [comment]
That's weird and that shouldn't have happened. Would you mind [uploading the .muse file here](http://muse.j-26.com/ep-uploads) so I can see what's going on?

Thanks for reporting the bug!

**Comment by jp26jp** [comment]
Got it. Taking a look now

**Comment by jp26jp** [comment]
I just pulled up Ecwid's version of the page and I'm not seeing those settings either. [You can see it here](https://store9350793.shopsettings.com/#!/Dye-R2-Loader/p/65678167/category=19198572). Is there another product that isn't showing the options?

**Comment by 512studio** [comment]
Yeah, there are a few others with lots of options.
I have no idea why it's not showing the options. Do you have a suggestion? I'm going to look through the account again to see if there's a setting I missed or turned off.
Thanks of looking into this.
I appreciate it!
 
 




    
 
  Carolina Fuguet
Owner/Creative Director 
5/12 Studio 
t: 754-800-5120   | e: carolina@512-studio.graphics  | w: www.512-Studio.graphics  | 
   
 
    
 IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof. 
 
 
--------- Original Message --------- Subject: Re: [j26design/Ecwid-Premium-Storefront] Missing Options (#2)

**Comment by 512studio** [comment]
Sorry, never mind. I realized what happened. The options were erased. Not sure why or how.
Thanks again for your help! :-)
Have a good one!
 
 




    
 
  Carolina Fuguet
Owner/Creative Director 
5/12 Studio 
t: 754-800-5120   | e: carolina@512-studio.graphics  | w: www.512-Studio.graphics  | 
   
 
    
 IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof. 
 
 
--------- Original Message --------- Subject: Re: [j26design/Ecwid-Premium-Storefront] Missing Options (#2)

**Comment by jp26jp** [comment]
Not a problem!
