### ISSUE TITLE
Ecwid widget for Muse display-chaos

### ISSUE THREAD

**Issue by macheibu** [j26design/Ecwid-Premium-Storefront#3]
Hello John Perry!
I thought I finally found the ultimate Ecwid widget, but without any configuration I have an issue, which you can "admire" in the attached screenshots.
• One screenshot taken from Muse’ built in preview without any further configuration (-> pic1.jpg)
• One Screenshot taken in browser preview (-> pic2.jpg). The shop view seems to be "pasted" into browser background.
What the hell is happening here?
Is there really no Ecwid widget for Muse working seamlessly out of the box?
![pic1](https://cloud.githubusercontent.com/assets/19224975/15074281/570c2150-139e-11e6-8285-c79db1d861ef.jpg)
![pic2](https://cloud.githubusercontent.com/assets/19224975/15074287/622762a2-139e-11e6-8a87-55a1261aa3f7.jpg)

**Comment by jp26jp** [comment]
No one's store has ever done anything remotely close to this so there has to be external code that is messing with your store. Please upload your Muse file here http://muse.j-26.com/ep-uploads

**Comment by macheibu** [comment]
Hello John!

Here you find a sample site using your Ecwid widget collection.
The display chaos is definitely not caused by „external code that is messing with your store“ as you state, but by a conflict between your „Top To Page“ widget and the Muse built in „Facebook“ widget.
Deleting one of them (or both)  makes all work well.

I uploaded a sample Muse file to your Dropbox

Regards
Günter

**Comment by jp26jp** [comment]
The background svg image that you are using is actually causing the issue. If that is removed, everything works well. SVGs as backgrounds do not work well in Muse especially in Safari browsers.

**Comment by macheibu** [comment]
You are testing, before you are writing, John???
First I never(!) had a problem with background SVGs, and second, if I replace it by a JPG, the issue is still there!.
You took into consideration the proposals I made:
"The display chaos is definitely not caused by „external code that is messing with your store“ as you state, but by a conflict between your „Top To Page“ widget and the Muse built in „Facebook“ widget. Deleting one of them (or both)  makes all work well."

Regards

**Comment by jp26jp** [comment]
I removed the Facebook widget and the top of the store widget and neither of them fixed the issue. The only thing that fixed the issue was removing the background svg which makes sense since the issue is coming from the background...

**Comment by jp26jp** [comment]
I've submitted the file to the Muse team so hopefully they can give us some insight into what is going on.

**Comment by jp26jp** [comment]
Both Ecwid and Muse heavily manipulate the [dom](https://en.wikipedia.org/wiki/Document_Object_Model) which is what causes background SVGs to display strangely.

**Comment by macheibu** [comment]
It is ok. Forget it.
Look here: http://www.tortenrosa.com/shop.html
All is working. _With_ background SVG, _with_ Facebook widget. _Without_ „Top of the Store“ widget.
I don’t ask why any more ...

Sincerely

**Comment by jp26jp** [comment]
Oh wow that's weird. That doesn't make any sense. I wonder what was happening to the preview that wasn't published? Well I'm glad it's working now!
