### ISSUE TITLE
Styling Text

### ISSUE THREAD

**Issue by h2oonstone** [j26design/Ecwid-Premium-Storefront#4]
1. I can’t seem to get h2 styling to work on any text when I apply code in the Ecwid Panel - I can get the other styles to apply.

2. I can’t get any styles to work on the text in the category (root or sub) text.

3. Can I match the style I have applied to the products to the category images?

**Comment by jp26jp** [comment]
1. Are you referring to the h2s in the product description?

2. I've fixed this in the next uodate!

3. I thought I had set up the styling to match for the product and category images but I will make sure this is fixed in the next uodate as well!

**Comment by h2oonstone** [comment]
Double checked - h2 works fine in product description - not in category description

**Comment by jp26jp** [comment]
Is there any way you could uplaod your [Muse site here](http://muse.j-26.com/ep-uploads) or publish the site to a temporary URL so I can see the H2 issue?

**Comment by h2oonstone** [comment]
Uploading now…

**Comment by jp26jp** [comment]
Awesome, I hadn't seen text being used in the category before so I didn't know it wasn't styled. I've updated the widget and the update also fixes a few other inconsistencies that I hadn't seen before. You'll need to update the main storefront widget, Global, and Buttons. They're in the Dropbox folder now, and I will get the email sent out a little later today!

The only thing I wasn't able to fix is the background and borders of the category image containers. The actual images follow the styling of the product images but the category containers are formatted in a way that is totally different from the product images for some reason.

BTW, your store looks amazing! I was so happy to see that you had utilized so many features of the widget!

I'm going to close this issue, but feel free to open it back up if I missed anything.

**Comment by h2oonstone** [comment]
You Rock - Thanks!
