### ISSUE TITLE
Premium Master Page V4.6.0

### ISSUE THREAD

**Issue by h2oonstone** [j26design/Ecwid-Premium-Storefront#5]
It's picking up the following as my url...
http://h2oonstone.com/artisan-distro

![screen shot 2016-05-19 at 1 44 20 pm](https://cloud.githubusercontent.com/assets/19439377/15403700/45b75a6c-1dc8-11e6-8e4b-d9735d159689.png)
![screen shot 2016-05-19 at 1 43 50 pm](https://cloud.githubusercontent.com/assets/19439377/15403704/49f4b548-1dc8-11e6-8ff5-024930c23f34.png)

**Comment by jp26jp** [comment]
Dang it. 4.6.0 was supposed to fix that. I'll take another look to see what's going on

**Comment by h2oonstone** [comment]
sorry : ( … Thanks!

**Comment by jp26jp** [comment]
I'm going to close this bug and move it to the Master Page (Premium) bug area. Updates for this bug [can be found here](https://github.com/j26design/Master-Page-Premium/issues/1)
